16-cookies-session/not-bluths-bananas/config/routes.rb
Rails.application.routes.draw do
  
  resources :orders, only: [:new, :create]
  resources :users, only: [:new, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # resources :bananas, only: [:index, :show, :new, :create, :edit, :update]
  # resources :bananas, except: [:destroy]
  resources :bananas

  delete '/sessions/reset_page_count', to: 'sessions#reset_page_count', as: 'reset_page_count'

  # get "/bananas", to: "bananas#index", as: "bananas"
  # get "/bananas/new", to: "bananas#new", as: "new_banana"
  # get "/bananas/:id", to: "bananas#show", as: "banana"
  # get "/bananas/:id/edit", to: "bananas#edit", as: "edit_banana"

  # post "/bananas", to: "bananas#create"
  # patch "/bananas/:id", to: "bananas#update"
  # delete "/bananas/:id", to: "bananas#destroy"

end

16-cookies-session/not-bluths-bananas/app/models/user.rb
class User < ApplicationRecord
  has_many :orders 
  has_many :bananas, through: :orders


  def display_name_and_age
    "#{self.name} | #{self.age}"
  end

end

16-cookies-session/not-bluths-bananas/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

16-cookies-session/not-bluths-bananas/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def reset_page_count
    # session[:view_count] = 0
    session.delete(:view_count)

    redirect_back fallback_location: bananas_path
  end

end

16-cookies-session/not-bluths-bananas/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new 
    @user = User.new
  end 
  
  def create 
    user = User.create(user_params)

    if user.valid? 
      redirect_to user_path(user)
    else
      flash[:errors] = user.errors.full_messages
      redirect_to new_user_path 
    end 
  end 


  private

  def user_params 
    params.require(:user).permit(:name, :email, :age)
  end 
end

16-cookies-session/not-bluths-bananas/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NotBluthsBananas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="banner">
      <%= image_tag "bluth_banner_gif.gif", class: "banner-img" %>
    </div>

    <ul class="nav">
      <li><a href="<%= bananas_path %>">Bananas</a></li>
      <li><a href="<%= new_banana_path %>">Create Banana</a></li>
      <li><a href="<%= new_order_path %>">Place Order</a></li>
    </ul>

    <%= yield %>
  </body>
</html>

16-cookies-session/not-bluths-bananas/app/views/users/new.html.erb
<h1>Create an Account</h1>

<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <p style="color:red;"><%= error %></p>
  <% end %>
<% end %>


<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field  :name %>

  <%= f.label :email %>
  <%= f.text_field  :email %>

  <%= f.label :age %>
  <%= f.number_field  :age %>

  <%= f.submit %>
<% end %>