17-auth-authentication/not-bluths-bananas/config/routes.rb
Rails.application.routes.draw do
  
  resources :orders, only: [:new, :create]
  resources :users, only: [:new, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # resources :bananas, only: [:index, :show, :new, :create, :edit, :update]
  # resources :bananas, except: [:destroy]
  resources :bananas

  delete '/sessions/reset_page_count', to: 'sessions#reset_page_count', as: 'reset_page_count'

  delete '/sessions/logout', to: 'sessions#logout', as: 'logout'

  get '/sessions/new_login', to: 'sessions#new_login', as: 'new_login'

  post '/sessions/new_login', to: 'sessions#login'

  # get "/bananas", to: "bananas#index", as: "bananas"
  # get "/bananas/new", to: "bananas#new", as: "new_banana"
  # get "/bananas/:id", to: "bananas#show", as: "banana"
  # get "/bananas/:id/edit", to: "bananas#edit", as: "edit_banana"

  # post "/bananas", to: "bananas#create"
  # patch "/bananas/:id", to: "bananas#update"
  # delete "/bananas/:id", to: "bananas#destroy"

end

17-auth-authentication/not-bluths-bananas/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :logged_in_user?

  def logged_in_user? 
    @current_user = User.find_by(id: session[:user_id])
  end 

end

17-auth-authentication/not-bluths-bananas/app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def new
    @order = Order.new

    @users = User.all
    @bananas = Banana.all
  end 


  def create 
    byebug
    order = Order.create(order_params)

    redirect_to banana_path(order.banana)
  end 

  private 
  
  def order_params
    params.require(:order).permit(:banana_id, :user_id)
  end 
end

17-auth-authentication/not-bluths-bananas/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def reset_page_count
    # session[:view_count] = 0
    session.delete(:view_count)

    redirect_back fallback_location: bananas_path
  end
  
  def logout 
    session.delete(:user_id)
    
    redirect_back fallback_location: bananas_path
  end 

  def new_login
  end 

  def login 
    # find user 
    @user = User.find_by(email: params[:session][:email])

    #compare passwords
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id 
      redirect_to bananas_path
    else 
      flash[:error] = "Password or Email did not match"
      redirect_to new_login_path
    end 
  end 

end

17-auth-authentication/not-bluths-bananas/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new 
    @user = User.new
  end 
  
  def create 
    user = User.create(user_params)

    if user.valid? 
      session[:user_id] = user.id
      
      redirect_to bananas_path
    else
      flash[:errors] = user.errors.full_messages
      redirect_to new_user_path 
    end 
  end 


  private

  def user_params 
    params.require(:user).permit(:password, :name, :email, :age)
  end 
end

17-auth-authentication/not-bluths-bananas/app/views/bananas/show.html.erb
<h1>Banana Show</h1>

<% if session[:view_count].to_i <= 2 %>

  <% if flash[:success] %>
    <h2 style="color:green;"><%= flash[:success] %></h2>
  <% end %>

  <h2 style="color:green;"><%= 2 - session[:view_count].to_i %> Page views left!!</h2>
  

  <h3><%= @banana.name %></h3>
  <p>Topping: <%= @banana.toppings %></p>
  <p>Price: <%= @banana.price %></p>


  <%= button_to "DELETE", banana_path(@banana), method: :delete %>

  <h4>Order Count <%= @banana.orders.count %></h4>
  <h2>All Users Who Have Ordered</h2>

  <% @banana.users.uniq.each do |user| %>
    <p><%= user.name %></p>
  <% end %>

<% else %>
  <h1>Show Some Ad</h1>
  <iframe width="966" height="543" src="https://www.youtube.com/embed/HXqjfpc1Kjg" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

  <%= button_to "I super promise I watched this ad", reset_page_count_path, method: :delete %>
  <%# create some button confirming they watched add and can see more pages %>
<% end %>

17-auth-authentication/not-bluths-bananas/app/views/orders/new.html.erb
<h1>Order Form</h1>

<%= form_for @order do |f| %>
  <%= f.label :user_id %>
  <%= f.collection_select :user_id, @users, :id, :display_name_and_age %>

  <%= f.label :banana_id %>
  <%= f.collection_select :banana_id, @bananas, :id, :name %>

  <%= f.submit %>

<% end %>


<%# <select name="user_id"> %>
  <%# <option value="1">name</option> %>
<%# </select> %>


<%# <form action=""> %>
  <%# <input type="text" name="sports[football]" > %>
  <%# <input type="text" name="sports[soccer]" > %>
  <%# <input type="text" name="sports[tennis]" > %>
  <%# <input type="text" name="cooking[pasta]" > %>
  <%# <input type="text" name="cooking[chicken]" > %>
<%# </form> %>